# Show a thin line around the windows
default_border pixel
shadows enable
corner_radius 6
# Gaps
gaps inner 3
gaps outer 5
smart_gaps off

blur on
blur_xray on
blur_passes 2
blur_radius 6

exec swaybg -o * -i /usr/share/backgrounds/StratOS/zstg/Stratos-Tokyonight-vectorized.png -m fill
# bar{
	# swaybar_command waybar
# }
#
# Cursor Theming
seat seat0 xcursor_theme Bibata-Modern-Classic 24
# Set colors for client windows
#client.focused          $color2 $color6 $foreground $color6 
client.focused			"#BAC3FF" "#060713" "#919DC7" "#0C0F2C"
