# status bar
exec waybar
exec sudo -E calamares -D8
# notifications
exec swaync
exec swayosd-server
exec systemctl --user start hyprpolkitagent
exec swww-daemon &
exec udiskie &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec /usr/lib/pam_kwallet_init
exec_always killall swayidle
#exec_always sh $HOME/.config/sway/swayidle.sh
#wayidle.sh
