# status bar
exec waybar
exec vicinae server &
exec sudo -E calamares -D8
# notifications
exec swaync
exec swaybg -i /usr/share/backgrounds/StratOS/zstg/StratOS-Tokyonight.png
exec swayosd-server
exec swww-daemon &
exec udiskie &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec /usr/lib/pam_kwallet_init
exec_always killall swayidle
exec /usr/local/bin/eww-toggle
#exec_always sh $HOME/.config/sway/swayidle.sh
#wayidle.sh
